name: rust cargo run
description: Rust Cargo Run

inputs:
  command:
    description: The cargo command to execute
    required: true
  args:
    description: The arguments to provide for the cargo command
    required: false
  components:
    description: The components to include when installing Rust
    required: false
  github_token:
    description: Github Token
    required: true
  save_cache:
    description: Whether to save the SSCACHE
    required: false

runs:
  using: composite
  steps:
  - name: Installing Rust
    uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
    with:
      profile: minimal
      target: wasm32-unknown-unknown
      override: true
      components: ${{ inputs.components }}
  - name: Setting up cache
    uses: pl-strflt/rust-sccache-action@v1
    env:
      GITHUB_TOKEN: ${{ inputs.github_token }}
      SCCACHE_CACHE_SIZE: 2G
      SCCACHE_DIR: ${{ github.workspace }}/.cache/sccache
      CACHE_SKIP_SAVE: ${{ inputs.save_cache == '' || inputs.save_cache == 'false' }}
    with:
      version: v0.2.15
      shared-key: v1  # change this to invalidate sccache for this job
  - name: Running ${{ inputs.command }}
    uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505 # v1.0.3
    env:
      CARGO_INCREMENTAL: '0'
    with:
      command: ${{ inputs.command }}
      args: ${{ inputs.args }}
