[advisories]
ignore = [
  "RUSTSEC-2024-0370", # proc-macro-error is unmaintained
  "RUSTSEC-2024-0384", # instant is unmaintained
  "RUSTSEC-2024-0421", # idna version is too old
  "RUSTSEC-2021-0145", # atty issue
  "RUSTSEC-2024-0375", # atty unmaintained
  "RUSTSEC-2024-0402", # hashbrown issue
]

[licenses]
allow = [
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "CC0-1.0",
  "MIT",
  "Unlicense",
  "Unicode-DFS-2016"
]
