[advisories]
ignore = [
  "RUSTSEC-2024-0384", # instant is unmaintained, required by ethers
]

[licenses]
allow = [
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "CC0-1.0",
  "MIT",
  "Unlicense",
  "Unicode-3.0"
]
