[package]
name = "fil_actor_sealer"
description = "Builtin sealer actor for Filecoin"
version.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true
authors = ["Curio Storage Inc. <info@curiostorage.org>"]
keywords = ["filecoin", "web3", "wasm"]

[lib]
## lib is necessary for integration tests
## cdylib is necessary for Wasm build
crate-type = ["cdylib", "lib"]

[dependencies]
fil_actors_runtime = { workspace = true }
fvm_shared = { workspace = true }
num-traits = { workspace = true }
num-derive = { workspace = true }
log = { workspace = true }
lazy_static = { workspace = true }
serde = { workspace = true }
fvm_ipld_blockstore = { workspace = true }
fvm_ipld_encoding = { workspace = true }
cid = { workspace = true }
fvm_ipld_bitfield = { workspace = true }
multihash-codetable = { workspace = true }
anyhow = { workspace = true }
frc42_dispatch = { workspace = true }


[dev-dependencies]
fil_actors_runtime = { workspace = true, features = ["test_utils", "sector-default"] }
num = { workspace = true }

[features]
fil-actor = ["fil_actors_runtime/fil-actor"]
