[build]
rustflags = [
    # Force unwrapping Result<_, Err>, especially for tests.
    "-D", "unused_must_use",
]

[target.wasm32-unknown-unknown]
rustflags = [
    "-Ctarget-feature=+bulk-memory",
    "-Ctarget-feature=+crt-static",
    "-Clink-arg=--export-table",
]
